### ISSUE TITLE
Assignment 1 submitting

### ISSUE THREAD

**Issue by hachanuy** [hachanuy/Restaurant#1]
Here is my submission for assignment 1, thank you.
@coderschoolreview

**Comment by hoksilato** [comment]
Hi @hachanuy  

Thanks for your submission :+1:, good work. Currently I got a problem when access https://warm-forest-13205.herokuapp.com/menu :(, did you forget to push your code to heroku.

The goal of this homework is to understand routes (RESTful and custom), use MVC correctly for simple pages, generate simple test data, use validations, use ActiveRecord for filtering, sorting and association.

Nice job with helper methods and the pagination. But if you have time, could you please try with the optional functionalities with future homeworks, I believe you can learn a lot from it.

/cc @coderschoolreview @harley

**Comment by hachanuy** [comment]
Sorry, for some reasons the database on heroku wasn't migrated, i already
fixed the problem, and sorry for not trying the optional functions but last
week i was busy with my assignments in school and my club activities, i
will try to finish more optional features.
